// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PalletSyncApi.Context;

#nullable disable

namespace PalletSyncApi.Migrations
{
    [DbContext(typeof(PalletSyncDbContext))]
    [Migration("20231130141844_Created_Forklift_Class")]
    partial class Created_Forklift_Class
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PalletSyncApi.Classes.Forklift", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastPalletId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LastPalletId");

                    b.HasIndex("LastUserId");

                    b.ToTable("Forklifts");

                    b.HasData(
                        new
                        {
                            Id = "F-0012",
                            LastPalletId = "P-0003",
                            LastUserId = "U-0001"
                        },
                        new
                        {
                            Id = "F-0007",
                            LastPalletId = "P-0003",
                            LastUserId = "U-0002"
                        },
                        new
                        {
                            Id = "F-0205",
                            LastPalletId = "P-0001",
                            LastUserId = "U-0003"
                        },
                        new
                        {
                            Id = "F-0016",
                            LastPalletId = "P-0005",
                            LastUserId = "U-0003"
                        });
                });

            modelBuilder.Entity("PalletSyncApi.Classes.Pallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pallets");

                    b.HasData(
                        new
                        {
                            Id = "P-0001",
                            Location = "Warehouse A",
                            State = 2
                        },
                        new
                        {
                            Id = "P-0002",
                            Location = "Warehouse A",
                            State = 2
                        },
                        new
                        {
                            Id = "P-0003",
                            Location = "Warehouse A",
                            State = 0
                        },
                        new
                        {
                            Id = "P-0004",
                            Location = "Warehouse A",
                            State = 1
                        },
                        new
                        {
                            Id = "P-0005",
                            Location = "Warehouse A",
                            State = 3
                        });
                });

            modelBuilder.Entity("PalletSyncApi.Classes.Shelf", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalletId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PalletId")
                        .IsUnique()
                        .HasFilter("[PalletId] IS NOT NULL");

                    b.ToTable("Shelves");

                    b.HasData(
                        new
                        {
                            Id = "S-0001",
                            Location = "Warehouse A",
                            PalletId = "P-0001"
                        },
                        new
                        {
                            Id = "S-0002",
                            Location = "Warehouse A",
                            PalletId = "P-0002"
                        },
                        new
                        {
                            Id = "S-0003",
                            Location = "Warehouse A"
                        },
                        new
                        {
                            Id = "S-0004",
                            Location = "Warehouse A"
                        },
                        new
                        {
                            Id = "S-0005",
                            Location = "Warehouse A"
                        });
                });

            modelBuilder.Entity("PalletSyncApi.Classes.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForkliftCertified")
                        .HasColumnType("bit");

                    b.Property<int>("IncorrectPalletPlacements")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U-0001",
                            FirstName = "Kacper",
                            ForkliftCertified = true,
                            IncorrectPalletPlacements = 0,
                            LastName = "Wroblewski",
                            Passcode = "245tbgt",
                            UserType = 1
                        },
                        new
                        {
                            Id = "U-0002",
                            FirstName = "Nikita",
                            ForkliftCertified = true,
                            IncorrectPalletPlacements = 13,
                            LastName = "Fedans",
                            Passcode = "245tbgt",
                            UserType = 0
                        },
                        new
                        {
                            Id = "U-0003",
                            FirstName = "Teodor",
                            ForkliftCertified = true,
                            IncorrectPalletPlacements = 3,
                            LastName = "Donchev",
                            Passcode = "245tbgt",
                            UserType = 0
                        },
                        new
                        {
                            Id = "U-0004",
                            FirstName = "Vincent",
                            ForkliftCertified = false,
                            IncorrectPalletPlacements = 0,
                            LastName = "Arellano",
                            Passcode = "245tbgt",
                            UserType = 0
                        },
                        new
                        {
                            Id = "U-0005",
                            FirstName = "Kyle",
                            ForkliftCertified = false,
                            IncorrectPalletPlacements = 0,
                            LastName = "McQuillan",
                            Passcode = "245tbgt",
                            UserType = 0
                        },
                        new
                        {
                            Id = "U-0006",
                            FirstName = "Siya",
                            ForkliftCertified = false,
                            IncorrectPalletPlacements = 0,
                            LastName = "Salekar",
                            Passcode = "245tbgt",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("PalletSyncApi.Classes.Forklift", b =>
                {
                    b.HasOne("PalletSyncApi.Classes.Pallet", "LastPallet")
                        .WithMany()
                        .HasForeignKey("LastPalletId");

                    b.HasOne("PalletSyncApi.Classes.User", "LastUser")
                        .WithMany()
                        .HasForeignKey("LastUserId");

                    b.Navigation("LastPallet");

                    b.Navigation("LastUser");
                });

            modelBuilder.Entity("PalletSyncApi.Classes.Shelf", b =>
                {
                    b.HasOne("PalletSyncApi.Classes.Pallet", "Pallet")
                        .WithOne()
                        .HasForeignKey("PalletSyncApi.Classes.Shelf", "PalletId");

                    b.Navigation("Pallet");
                });
#pragma warning restore 612, 618
        }
    }
}
